### ISSUE TITLE
NPE TextChannel#sendMessage PermissionUtil.checkPermission

### ISSUE THREAD

**Issue by sponges** [sponges/dabBotDiscord#2]
```
Mar 08, 2017 5:13:19 PM ovh.not.dabbot.Command$Context reply
WARNING: java.lang.NullPointerException
	at net.dv8tion.jda.core.utils.PermissionUtil.checkPermission(PermissionUtil.java:278)
	at net.dv8tion.jda.core.entities.impl.MemberImpl.hasPermission(MemberImpl.java:159)
	at net.dv8tion.jda.core.entities.impl.TextChannelImpl.checkPermission(TextChannelImpl.java:580)
	at net.dv8tion.jda.core.entities.impl.TextChannelImpl.checkPermission(TextChannelImpl.java:577)
	at net.dv8tion.jda.core.entities.impl.TextChannelImpl.sendMessage(TextChannelImpl.java:256)
	at net.dv8tion.jda.core.entities.MessageChannel.sendMessage(MessageChannel.java:113)
	at ovh.not.dabbot.Command$Context.reply(Command.kt:33)
	at ovh.not.dabbot.Command$Context.reply(Command.kt:42)
	at ovh.not.dabbot.command.AnnouncementsCommand.on(AnnouncementsCommand.kt:10)
	at ovh.not.dabbot.Listener.onMessageReceived(Listener.kt:40)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:326)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:122)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:48)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:727)
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:464)
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262)
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240)
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)
```

Happens sometimes, can't figure out the cause. Above exception happened whilst sending a song announcement into a music channel.

**Comment by sponges** [comment]
Fixed by https://github.com/DV8FromTheWorld/JDA/commit/14001152eb24a01d529372d0f794779e5020b278

**Comment by sponges** [comment]
test
